In [1]:
import pandas as pd
import requests
import datetime as dt
import numpy as np

In [2]:
# Load data
National_Parks_cleaned_df = pd.read_csv('National_Parks_cleaned.csv')
National_Parks_cleaned_df

,park_code,park_name,fee_per_car,fee_per_person,street_address,city,state,zip,phone,email,lat,lng,weather_summary
0,acad,Acadia National Park,30.0,15.0,25 Visitor Center Road,Bar Harbor,ME,04609,2072883338,acadia_information@nps.gov,44.409286,-68.247501,"Located on Mount Desert Island in Maine, Acadi..."
1,agfo,Agate Fossil Beds National Monument,0.0,0.0,301 River Road,Harrison,NE,69346,NaN,agfo_ranger_activities@nps.gov,42.421704,-103.753886,"Summers can be very warm, high 90's to 100 wit..."
2,alka,Ala Kahakai National Historic Trail,0.0,0.0,Superintendent,Kailua-Kona,HI,96740,NaN,aric_arakaki@nps.gov,19.144668,-155.890734,Hawaiʻiʻs coast is generally sunny and hot. Be...
3,alfl,Alibates Flint Quarries National Monument,0.0,0.0,37084 Alibates Rd.,Potter County,TX,79036,NaN,lamr_interpretation@nps.gov,35.581966,-101.671701,The Texas Panhandle experiences a wide variety...
4,alpo,Allegheny Portage Railroad National Historic Site,0.0,0.0,110 Federal Park Road,Gallitzin,PA,16641,NaN,alpo_interpretation@nps.gov,40.429775,-78.574316,"The park is located in Cambria County, PA, and..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,yell,Yellowstone National Park,35.0,20.0,2 Officers Row,Yellowstone National Park,WY,82190,307-344-7381,YELL_Information@nps.gov,44.598244,-110.547169,"Yellowstone's weather can vary quite a bit, ev..."
271,york,Yorktown Battlefield Part of Colonial National...,0.0,0.0,Yorktown Battlefield,Yorktown,VA,23690,NaN,colo_info@nps.gov,37.219500,-76.498300,"Yorktown, VA climate is warm during summer whe..."
272,yose,Yosemite National Park,35.0,20.0,9039 Village Drive,Yosemite,CA,95389,209/372-0200,yose_web_manager@nps.gov,37.848833,-119.557187,"Yosemite National Park covers nearly 1,200 squ..."
273,yuch,Yukon - Charley Rivers National Preserve,0.0,0.0,101 Dunkel St,Fairbanks,AK,99701,NaN,fair_information@nps.gov,65.093561,-142.796002,The area that Yukon-Charley Rivers encompasses...
274,zion,Zion National Park,35.0,20.0,Zion National Park,Springdale,UT,84767,435-772-3256,zion_park_information@nps.gov,37.298393,-113.026514,Zion is known for a wide range of weather cond...

In [3]:
all_trails_filtered_df = pd.read_csv('alltrails_filtered.csv')
all_trails_filtered_df

,trail_id,trail,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,avg_rating,num_reviews,features,activities,units,park_code
0,10006571,Angels Landing Trail,"{'lat': 37.25928, 'lng': -112.95166}",84.6229,6598.294,492.8616,5,out and back,5.0,3903,"['dogs-no', 'partially-paved', 'river', 'views...","['hiking', 'nature-trips', 'trail-running']",i,zion
1,10026705,Emerald Lake Trail,"{'lat': 40.31177, 'lng': -105.64533}",83.0341,4988.954,215.7984,3,out and back,4.5,2991,"['dogs-no', 'forest', 'lake', 'kids', 'partial...","['birding', 'fishing', 'hiking', 'nature-trips...",i,romo
2,10026910,Vernal and Nevada Falls via the Mist Trail,"{'lat': 37.73495, 'lng': -119.56619}",68.1488,10299.776,667.8168,3,loop,5.0,1869,"['dogs-no', 'forest', 'partially-paved', 'rive...","['birding', 'hiking', 'nature-trips', 'walking']",i,yose
3,10235688,Sky Pond via Glacier Gorge Trail,"{'lat': 40.31052, 'lng': -105.64032}",65.4770,13035.654,537.9720,5,out and back,5.0,1599,"['dogs-no', 'forest', 'lake', 'river', 'views'...","['birding', 'hiking', 'nature-trips', 'snowsho...",i,romo
4,10012464,Delicate Arch Trail,"{'lat': 38.73568, 'lng': -109.5205}",63.6748,4988.954,186.8424,3,out and back,5.0,2332,"['dogs-no', 'kids', 'partially-paved', 'views'...","['birding', 'hiking', 'nature-trips', 'rock-cl...",i,arch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2078,10278538,Kayenta Trail to the Emerald Pools and Zion Lo...,"{'lat': 37.25918, 'lng': -112.95125}",1.6750,6920.162,313.9440,3,out and back,4.0,26,"['dogs-no', 'lake', 'kids', 'river', 'views', ...","['hiking', 'nature-trips', 'walking']",i,zion
2079,10111637,Careys Castle Trail [CLOSED],"{'lat': 33.69963, 'lng': -115.6785}",1.5663,12070.050,388.9248,3,out and back,3.5,10,"['dogs-no', 'views', 'wild-flowers', 'wildlife']","['birding', 'hiking', 'nature-trips', 'trail-r...",i,jotr
2080,10235829,Old Carriage Trail [CLOSED],"{'lat': 41.28957, 'lng': -81.56437}",1.4010,8529.502,105.7656,3,loop,3.5,41,"['dogs-leash', 'forest', 'kids', 'partially-pa...","['hiking', 'nature-trips', 'trail-running', 'w...",i,cuva
2081,10255922,Spruce Tree House Trail [CLOSED],"{'lat': 37.1843, 'lng': -108.48833}",1.2883,804.670,47.8536,1,loop,4.0,15,"['ada', 'dogs-no', 'kids', 'paved', 'strollers...","['birding', 'hiking', 'nature-trips', 'trail-r...",i,meve
2082,10541288,Hoh River Trail to Mineral Creek Falls,"{'lat': 47.8601, 'lng': -123.93447}",0.0000,8851.370,64.9224,1,out and back,4.5,75,"['dogs-no', 'forest', 'river', 'views', 'water...","['hiking', 'nature-trips', 'walking']",i,olym

In [4]:
exploratory_df = National_Parks_cleaned_df
exploratory_df.describe()

       fee_per_car  fee_per_person         lat         lng
count   275.000000      275.000000  275.000000  275.000000
mean      6.174545        4.350909   39.007123 -100.482917
std      11.242130        7.940101    8.628299   22.352017
min       0.000000        0.000000  -14.228659 -169.850378
25%       0.000000        0.000000   35.340932 -112.353467
50%       0.000000        0.000000   38.465846 -101.682007
75%       9.000000       10.000000   42.028800  -80.818099
max      35.000000       40.000000   68.010271  -64.622218

In [5]:
exploratory_df2 = all_trails_filtered_df
exploratory_df2.describe()

,trail_id,popularity,length,elevation_gain,difficulty_rating,avg_rating,num_reviews
count,2.083000e+03,2083.000000,2083.000000,2083.000000,2083.000000,2083.000000,2083.000000
mean,1.015092e+07,12.202256,12923.162447,468.370049,2.909746,4.377100,109.433509
std,1.350299e+05,8.670774,21214.442860,652.043182,1.656216,0.375804,223.151759
min,1.000001e+07,0.000000,0.000000,0.000000,1.000000,3.000000,10.000000
25%,1.002656e+07,6.714100,3540.548000,83.820000,1.000000,4.000000,19.000000
50%,1.011152e+07,9.562100,7885.766000,278.892000,3.000000,4.500000,41.000000
75%,1.026647e+07,14.543200,15610.598000,629.716800,3.000000,4.500000,101.000000
max,1.054129e+07,84.622900,529794.728000,14029.944000,7.000000,5.000000,3903.000000

In [6]:
all_trails_filtered_df2 = all_trails_filtered_df.groupby(['park_code']).count()['trail_id']
all_trails_filtered_df2

park_code
acad    133
arch     34
badl      9
bibe     44
blca     20
brca     28
cany     38
care     29
cave      2
chis     11
cong      6
crla     18
cuva     45
dena     11
deva     31
ever     12
glac     81
glba      1
grba     14
grca     63
grsa     10
grsm    181
grte     65
gumo     15
hale     13
havo     21
hosp     15
indu     10
isro      1
jotr     59
kefj      2
lavo     32
maca     21
meve     17
mora    106
noca     10
olym    101
pefo     12
pinn     18
redw     13
romo    149
sagu     43
seki     76
shen    121
thro     15
voya      3
wica      8
wotr      1
yell    123
yose    127
zion     65
Name: trail_id, dtype: int64

In [7]:
all_trails_filtered_df3 = all_trails_filtered_df.groupby(['park_code']).mean()['difficulty_rating']
all_trails_filtered_df3

park_code
acad    2.879699
arch    1.941176
badl    2.333333
bibe    2.500000
blca    2.100000
brca    2.500000
cany    2.684211
care    2.655172
cave    1.000000
chis    2.636364
cong    1.000000
crla    2.111111
cuva    2.377778
dena    2.454545
deva    2.161290
ever    1.000000
glac    3.469136
glba    1.000000
grba    3.142857
grca    3.730159
grsa    3.400000
grsm    3.408840
grte    3.215385
gumo    3.800000
hale    3.461538
havo    2.714286
hosp    2.733333
indu    2.000000
isro    5.000000
jotr    2.525424
kefj    3.000000
lavo    2.687500
maca    1.857143
meve    1.705882
mora    3.094340
noca    3.800000
olym    3.356436
pefo    1.500000
pinn    3.666667
redw    2.692308
romo    3.187919
sagu    2.395349
seki    3.026316
shen    2.851240
thro    2.733333
voya    1.666667
wica    2.250000
wotr    1.000000
yell    2.219512
yose    3.440945
zion    3.000000
Name: difficulty_rating, dtype: float64

In [8]:
all_trails_filtered_df4 = all_trails_filtered_df.groupby(['park_code']).mean()['avg_rating']
all_trails_filtered_df4

park_code
acad    4.473684
arch    4.397059
badl    4.166667
bibe    4.238636
blca    4.350000
brca    4.428571
cany    4.407895
care    4.465517
cave    4.500000
chis    4.454545
cong    3.833333
crla    4.250000
cuva    4.222222
dena    4.272727
deva    4.290323
ever    3.833333
glac    4.444444
glba    4.500000
grba    4.464286
grca    4.555556
grsa    4.250000
grsm    4.284530
grte    4.523077
gumo    4.400000
hale    4.615385
havo    4.238095
hosp    3.966667
indu    4.200000
isro    4.000000
jotr    4.322034
kefj    4.750000
lavo    4.390625
maca    3.904762
meve    4.205882
mora    4.452830
noca    4.450000
olym    4.425743
pefo    4.208333
pinn    4.444444
redw    4.423077
romo    4.483221
sagu    4.174419
seki    4.526316
shen    4.194215
thro    4.300000
voya    3.833333
wica    4.187500
wotr    4.500000
yell    4.341463
yose    4.590551
zion    4.323077
Name: avg_rating, dtype: float64

In [10]:
summary_table = pd.DataFrame({'num_of_trails':all_trails_filtered_df.groupby('park_code').count()['trail_id'],
                'avg_difficulty':all_trails_filtered_df.groupby('park_code').mean()['difficulty_rating'],
                'avg_rating':all_trails_filtered_df.groupby('park_code').mean()['avg_rating']})

summary_table = summary_table.reset_index(drop=False)
summary_table

   park_code  num_of_trails  avg_difficulty  avg_rating
0       acad            133        2.879699    4.473684
1       arch             34        1.941176    4.397059
2       badl              9        2.333333    4.166667
3       bibe             44        2.500000    4.238636
4       blca             20        2.100000    4.350000
5       brca             28        2.500000    4.428571
6       cany             38        2.684211    4.407895
7       care             29        2.655172    4.465517
8       cave              2        1.000000    4.500000
9       chis             11        2.636364    4.454545
10      cong              6        1.000000    3.833333
11      crla             18        2.111111    4.250000
12      cuva             45        2.377778    4.222222
13      dena             11        2.454545    4.272727
14      deva             31        2.161290    4.290323
15      ever             12        1.000000    3.833333
16      glac             81        3.469136    4.444444
17      glba              1        1.000000    4.500000
18      grba             14        3.142857    4.464286
19      grca             63        3.730159    4.555556
20      grsa             10        3.400000    4.250000
21      grsm            181        3.408840    4.284530
22      grte             65        3.215385    4.523077
23      gumo             15        3.800000    4.400000
24      hale             13        3.461538    4.615385
25      havo             21        2.714286    4.238095
26      hosp             15        2.733333    3.966667
27      indu             10        2.000000    4.200000
28      isro              1        5.000000    4.000000
29      jotr             59        2.525424    4.322034
30      kefj              2        3.000000    4.750000
31      lavo             32        2.687500    4.390625
32      maca             21        1.857143    3.904762
33      meve             17        1.705882    4.205882
34      mora            106        3.094340    4.452830
35      noca             10        3.800000    4.450000
36      olym            101        3.356436    4.425743
37      pefo             12        1.500000    4.208333
38      pinn             18        3.666667    4.444444
39      redw             13        2.692308    4.423077
40      romo            149        3.187919    4.483221
41      sagu             43        2.395349    4.174419
42      seki             76        3.026316    4.526316
43      shen            121        2.851240    4.194215
44      thro             15        2.733333    4.300000
45      voya              3        1.666667    3.833333
46      wica              8        2.250000    4.187500
47      wotr              1        1.000000    4.500000
48      yell            123        2.219512    4.341463
49      yose            127        3.440945    4.590551
50      zion             65        3.000000    4.323077

In [11]:
Combined_Data = summary_table.merge(National_Parks_cleaned_df, how = 'outer', on='park_code')
Combined_Data

,park_code,num_of_trails,avg_difficulty,avg_rating,park_name,fee_per_car,fee_per_person,street_address,city,state,zip,phone,email,lat,lng,weather_summary
0,acad,133.0,2.879699,4.473684,Acadia National Park,30.0,15.0,25 Visitor Center Road,Bar Harbor,ME,04609,2072883338,acadia_information@nps.gov,44.409286,-68.247501,"Located on Mount Desert Island in Maine, Acadi..."
1,arch,34.0,1.941176,4.397059,Arches National Park,30.0,15.0,"5 miles north of Moab, Utah, on US 191",Moab,UT,84532,4357192299,archinfo@nps.gov,38.722618,-109.586367,"Arches is part of the Colorado Plateau, a ""hig..."
2,badl,9.0,2.333333,4.166667,Badlands National Park,30.0,25.0,25216 Ben Reifel Road,Interior,SD,57750,6054335361,badl_information@nps.gov,43.685848,-102.482942,The Badlands weather is variable and unpredict...
3,bibe,44.0,2.500000,4.238636,Big Bend National Park,30.0,12.0,1 Panther Junction,Big Bend National Park,TX,79834,432-477-2251,bibe_info@nps.gov,29.298178,-103.229790,"Big Bend is a desert park, so be prepared for ..."
4,blca,20.0,2.100000,4.350000,Black Canyon Of The Gunnison National Park,30.0,15.0,South Rim Visitor Center,Montrose,CO,81401,970-641-2337,blca_info@nps.gov,38.577799,-107.724276,Today's Weather: http://www.weather.com/weathe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,wicr,NaN,NaN,NaN,Wilson's Creek National Battlefield,10.0,15.0,6424 W. Farm Road 182,Republic,MO,65738,4177322662,billie_aschwege@nps.gov,37.100013,-93.409867,"Summer months are frequently hot and humid, wi..."
271,wrst,NaN,NaN,NaN,Wrangell - St Elias National Park & Preserve,0.0,0.0,Wrangell-St. Elias National Park & Preserve,Copper Center,AK,99573,NaN,wrst_info@nps.gov,61.418215,-142.602844,Varies widely depending on location in park an...
272,wupa,NaN,NaN,NaN,Wupatki National Monument,25.0,40.0,25137 N. Sunset Crater-Wupatki Loop Rd.,Flagstaff,AZ,86004,9286792365 or 9288561705,flag_information@nps.gov,35.557411,-111.395722,Be prepared for variable and extreme weather c...
273,york,NaN,NaN,NaN,Yorktown Battlefield Part of Colonial National...,0.0,0.0,Yorktown Battlefield,Yorktown,VA,23690,NaN,colo_info@nps.gov,37.219500,-76.498300,"Yorktown, VA climate is warm during summer whe..."
274,yuch,NaN,NaN,NaN,Yukon - Charley Rivers National Preserve,0.0,0.0,101 Dunkel St,Fairbanks,AK,99701,NaN,fair_information@nps.gov,65.093561,-142.796002,The area that Yukon-Charley Rivers encompasses...

In [12]:
Combined_Data = Combined_Data.fillna(0)
Combined_Data

,park_code,num_of_trails,avg_difficulty,avg_rating,park_name,fee_per_car,fee_per_person,street_address,city,state,zip,phone,email,lat,lng,weather_summary
0,acad,133.0,2.879699,4.473684,Acadia National Park,30.0,15.0,25 Visitor Center Road,Bar Harbor,ME,04609,2072883338,acadia_information@nps.gov,44.409286,-68.247501,"Located on Mount Desert Island in Maine, Acadi..."
1,arch,34.0,1.941176,4.397059,Arches National Park,30.0,15.0,"5 miles north of Moab, Utah, on US 191",Moab,UT,84532,4357192299,archinfo@nps.gov,38.722618,-109.586367,"Arches is part of the Colorado Plateau, a ""hig..."
2,badl,9.0,2.333333,4.166667,Badlands National Park,30.0,25.0,25216 Ben Reifel Road,Interior,SD,57750,6054335361,badl_information@nps.gov,43.685848,-102.482942,The Badlands weather is variable and unpredict...
3,bibe,44.0,2.500000,4.238636,Big Bend National Park,30.0,12.0,1 Panther Junction,Big Bend National Park,TX,79834,432-477-2251,bibe_info@nps.gov,29.298178,-103.229790,"Big Bend is a desert park, so be prepared for ..."
4,blca,20.0,2.100000,4.350000,Black Canyon Of The Gunnison National Park,30.0,15.0,South Rim Visitor Center,Montrose,CO,81401,970-641-2337,blca_info@nps.gov,38.577799,-107.724276,Today's Weather: http://www.weather.com/weathe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,wicr,0.0,0.000000,0.000000,Wilson's Creek National Battlefield,10.0,15.0,6424 W. Farm Road 182,Republic,MO,65738,4177322662,billie_aschwege@nps.gov,37.100013,-93.409867,"Summer months are frequently hot and humid, wi..."
271,wrst,0.0,0.000000,0.000000,Wrangell - St Elias National Park & Preserve,0.0,0.0,Wrangell-St. Elias National Park & Preserve,Copper Center,AK,99573,0,wrst_info@nps.gov,61.418215,-142.602844,Varies widely depending on location in park an...
272,wupa,0.0,0.000000,0.000000,Wupatki National Monument,25.0,40.0,25137 N. Sunset Crater-Wupatki Loop Rd.,Flagstaff,AZ,86004,9286792365 or 9288561705,flag_information@nps.gov,35.557411,-111.395722,Be prepared for variable and extreme weather c...
273,york,0.0,0.000000,0.000000,Yorktown Battlefield Part of Colonial National...,0.0,0.0,Yorktown Battlefield,Yorktown,VA,23690,0,colo_info@nps.gov,37.219500,-76.498300,"Yorktown, VA climate is warm during summer whe..."
274,yuch,0.0,0.000000,0.000000,Yukon - Charley Rivers National Preserve,0.0,0.0,101 Dunkel St,Fairbanks,AK,99701,0,fair_information@nps.gov,65.093561,-142.796002,The area that Yukon-Charley Rivers encompasses...

In [15]:
## convert to csv 
Combined_Data.to_csv('national_parks_cleaned_with_avgs.csv',index=False)