In [1]:
import pandas as pd
import requests
import datetime as dt
import numpy as np

In [2]:
# Load the National Parks data into park_df
park_df = pd.read_csv('Resources/National_Parks.csv')
park_df

,parkCode,Park Name,Fee per Car,Fee per Person,Street Address,City,State,Zip Code,Phone Number,Email Address,Lat,Lng,Weather Summary
0,acad,Acadia National Park,30.0,15.0,25 Visitor Center Road,Bar Harbor,ME,04609,2072883338,acadia_information@nps.gov,44.409286,-68.247501,"Located on Mount Desert Island in Maine, Acadi..."
1,agfo,Agate Fossil Beds National Monument,0.0,0.0,301 River Road,Harrison,NE,69346,NaN,agfo_ranger_activities@nps.gov,42.421704,-103.753886,"Summers can be very warm, high 90's to 100 wit..."
2,alka,Ala Kahakai National Historic Trail,0.0,0.0,Superintendent,Kailua-Kona,HI,96740,NaN,aric_arakaki@nps.gov,19.144668,-155.890734,Hawaiʻiʻs coast is generally sunny and hot. Be...
3,alfl,Alibates Flint Quarries National Monument,0.0,0.0,37084 Alibates Rd.,Potter County,TX,79036,NaN,lamr_interpretation@nps.gov,35.581966,-101.671701,The Texas Panhandle experiences a wide variety...
4,alpo,Allegheny Portage Railroad National Historic Site,0.0,0.0,110 Federal Park Road,Gallitzin,PA,16641,NaN,alpo_interpretation@nps.gov,40.429775,-78.574316,"The park is located in Cambria County, PA, and..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,yell,Yellowstone National Park,35.0,20.0,2 Officers Row,Yellowstone National Park,WY,82190,307-344-7381,YELL_Information@nps.gov,44.598244,-110.547169,"Yellowstone's weather can vary quite a bit, ev..."
271,york,Yorktown Battlefield Part of Colonial National...,0.0,0.0,Yorktown Battlefield,Yorktown,VA,23690,NaN,colo_info@nps.gov,37.219500,-76.498300,"Yorktown, VA climate is warm during summer whe..."
272,yose,Yosemite National Park,35.0,20.0,9039 Village Drive,Yosemite,CA,95389,209/372-0200,yose_web_manager@nps.gov,37.848833,-119.557187,"Yosemite National Park covers nearly 1,200 squ..."
273,yuch,Yukon - Charley Rivers National Preserve,0.0,0.0,101 Dunkel St,Fairbanks,AK,99701,NaN,fair_information@nps.gov,65.093561,-142.796002,The area that Yukon-Charley Rivers encompasses...
274,zion,Zion National Park,35.0,20.0,Zion National Park,Springdale,UT,84767,435-772-3256,zion_park_information@nps.gov,37.298393,-113.026514,Zion is known for a wide range of weather cond...

In [3]:
# Rename the columns to names without blanks 
park_df.rename(columns= {"parkCode": "park_code", "Park Name": "park_name", "Fee per Car":"fee_per_car",
                        "Fee per Person":"fee_per_person","Street Address":"street_address","City":"city",
                        "State": "state","Zip Code":"zip","Phone Number":"phone","Email Address":"email",
                        "Lat":"lat","Lng":"lng","Weather Summary":"weather_summary"
                        }, inplace = True)
park_df

,park_code,park_name,fee_per_car,fee_per_person,street_address,city,state,zip,phone,email,lat,lng,weather_summary
0,acad,Acadia National Park,30.0,15.0,25 Visitor Center Road,Bar Harbor,ME,04609,2072883338,acadia_information@nps.gov,44.409286,-68.247501,"Located on Mount Desert Island in Maine, Acadi..."
1,agfo,Agate Fossil Beds National Monument,0.0,0.0,301 River Road,Harrison,NE,69346,NaN,agfo_ranger_activities@nps.gov,42.421704,-103.753886,"Summers can be very warm, high 90's to 100 wit..."
2,alka,Ala Kahakai National Historic Trail,0.0,0.0,Superintendent,Kailua-Kona,HI,96740,NaN,aric_arakaki@nps.gov,19.144668,-155.890734,Hawaiʻiʻs coast is generally sunny and hot. Be...
3,alfl,Alibates Flint Quarries National Monument,0.0,0.0,37084 Alibates Rd.,Potter County,TX,79036,NaN,lamr_interpretation@nps.gov,35.581966,-101.671701,The Texas Panhandle experiences a wide variety...
4,alpo,Allegheny Portage Railroad National Historic Site,0.0,0.0,110 Federal Park Road,Gallitzin,PA,16641,NaN,alpo_interpretation@nps.gov,40.429775,-78.574316,"The park is located in Cambria County, PA, and..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,yell,Yellowstone National Park,35.0,20.0,2 Officers Row,Yellowstone National Park,WY,82190,307-344-7381,YELL_Information@nps.gov,44.598244,-110.547169,"Yellowstone's weather can vary quite a bit, ev..."
271,york,Yorktown Battlefield Part of Colonial National...,0.0,0.0,Yorktown Battlefield,Yorktown,VA,23690,NaN,colo_info@nps.gov,37.219500,-76.498300,"Yorktown, VA climate is warm during summer whe..."
272,yose,Yosemite National Park,35.0,20.0,9039 Village Drive,Yosemite,CA,95389,209/372-0200,yose_web_manager@nps.gov,37.848833,-119.557187,"Yosemite National Park covers nearly 1,200 squ..."
273,yuch,Yukon - Charley Rivers National Preserve,0.0,0.0,101 Dunkel St,Fairbanks,AK,99701,NaN,fair_information@nps.gov,65.093561,-142.796002,The area that Yukon-Charley Rivers encompasses...
274,zion,Zion National Park,35.0,20.0,Zion National Park,Springdale,UT,84767,435-772-3256,zion_park_information@nps.gov,37.298393,-113.026514,Zion is known for a wide range of weather cond...

In [4]:
#Save it to National Parks Cleaned CSV file
park_df.to_csv('Resources/National_Parks_cleaned.csv',index=False)

In [5]:
# Get the trail data into a dataframe
alltrails_df = pd.read_csv('Resources/AllTrails data - nationalpark.csv')

# Rename the columns
alltrails_df.rename(columns= {"name": "trail", "area_name": "park_name"}, inplace = True)

# Drop the unwanted columns
alltrails_df.drop(['city_name','state_name','country_name','visitor_usage'], axis = 1)

# Change the index to park name
alltrails_df.set_index('park_name')

alltrails_df

,trail_id,trail,park_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18852, 'lng': -149.63156}",24.8931,15610.598,1161.8976,5,out and back,3.0,5.0,423,"['dogs-no', 'forest', 'river', 'views', 'water...","['birding', 'camping', 'hiking', 'nature-trips...",i
1,10236086,Mount Healy Overlook Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73049, 'lng': -148.91968}",18.0311,6920.162,507.7968,3,out and back,1.0,4.5,260,"['dogs-no', 'forest', 'views', 'wild-flowers',...","['birding', 'camping', 'hiking', 'nature-trips...",i
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18879, 'lng': -149.631}",17.7821,2896.812,81.9912,1,out and back,3.0,4.5,224,"['dogs-no', 'partially-paved', 'views', 'wildl...","['hiking', 'walking']",i
3,10236076,Horseshoe Lake Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73661, 'lng': -148.915}",16.2674,3379.614,119.7864,1,loop,2.0,4.5,237,"['dogs-no', 'forest', 'lake', 'kids', 'views',...","['birding', 'hiking', 'nature-trips', 'trail-r...",i
4,10236082,Triple Lakes Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73319, 'lng': -148.89682}",12.5935,29772.790,1124.7120,5,out and back,1.0,4.5,110,"['dogs-no', 'lake', 'views', 'wild-flowers', '...","['birding', 'fishing', 'hiking', 'nature-trips...",i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,10008302,Silversword Loop Via Halemau'u Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.75275, 'lng': -156.22884}",9.3861,20116.750,1105.8144,5,loop,2.0,4.5,43,"['dogs-no', 'views', 'wild-flowers']","['birding', 'hiking', 'nature-trips']",m
3309,10236001,Keonehe'ehe'e Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.714480000000002, 'lng': -156.25072}",9.1555,28324.384,1171.9560,5,out and back,2.0,5.0,22,"['dogs-no', 'views', 'wildlife']","['backpacking', 'camping', 'hiking']",m
3310,10258707,Red Hill Overlook Summit Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.71007, 'lng': -156.25357}",8.5066,321.868,3.9624,1,out and back,NaN,4.5,31,"['dogs-no', 'kids', 'views']","['hiking', 'walking']",m
3311,10014989,Kaupo Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.64981, 'lng': -156.137}",8.3240,19312.080,1670.9136,5,out and back,1.0,4.0,8,"['dogs-no', 'views', 'wildlife']",['hiking'],m
3312,10259465,Ka Lu'u o ka O'o Cinder Cone via Crater and Sl...,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.71449, 'lng': -156.25085}",2.4176,8368.568,510.8448,3,loop,2.0,4.5,45,['views'],['hiking'],m

In [6]:
# From the National parks dataframe, copy the park name and park code into another dataframe - park_code_df
park_code_df = park_df[["park_name","park_code"]].copy()
park_code_df

# Make the Park name it's index
park_code_df.set_index('park_name')

                                                   park_code
park_name
Acadia National Park                                    acad
Agate Fossil Beds National Monument                     agfo
Ala Kahakai National Historic Trail                     alka
Alibates Flint Quarries National Monument               alfl
Allegheny Portage Railroad National Historic Site       alpo
...                                                      ...
Yellowstone National Park                               yell
Yorktown Battlefield Part of Colonial National ...      york
Yosemite National Park                                  yose
Yukon - Charley Rivers National Preserve                yuch
Zion National Park                                      zion

[275 rows x 1 columns]

In [7]:
# Add the park code to the all trail dataframe
trails_park_code_df = alltrails_df.merge(park_code_df, how='left')

trails_park_code_df

,trail_id,trail,park_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units,park_code
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18852, 'lng': -149.63156}",24.8931,15610.598,1161.8976,5,out and back,3.0,5.0,423,"['dogs-no', 'forest', 'river', 'views', 'water...","['birding', 'camping', 'hiking', 'nature-trips...",i,kefj
1,10236086,Mount Healy Overlook Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73049, 'lng': -148.91968}",18.0311,6920.162,507.7968,3,out and back,1.0,4.5,260,"['dogs-no', 'forest', 'views', 'wild-flowers',...","['birding', 'camping', 'hiking', 'nature-trips...",i,NaN
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18879, 'lng': -149.631}",17.7821,2896.812,81.9912,1,out and back,3.0,4.5,224,"['dogs-no', 'partially-paved', 'views', 'wildl...","['hiking', 'walking']",i,kefj
3,10236076,Horseshoe Lake Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73661, 'lng': -148.915}",16.2674,3379.614,119.7864,1,loop,2.0,4.5,237,"['dogs-no', 'forest', 'lake', 'kids', 'views',...","['birding', 'hiking', 'nature-trips', 'trail-r...",i,NaN
4,10236082,Triple Lakes Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73319, 'lng': -148.89682}",12.5935,29772.790,1124.7120,5,out and back,1.0,4.5,110,"['dogs-no', 'lake', 'views', 'wild-flowers', '...","['birding', 'fishing', 'hiking', 'nature-trips...",i,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,10008302,Silversword Loop Via Halemau'u Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.75275, 'lng': -156.22884}",9.3861,20116.750,1105.8144,5,loop,2.0,4.5,43,"['dogs-no', 'views', 'wild-flowers']","['birding', 'hiking', 'nature-trips']",m,NaN
3309,10236001,Keonehe'ehe'e Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.714480000000002, 'lng': -156.25072}",9.1555,28324.384,1171.9560,5,out and back,2.0,5.0,22,"['dogs-no', 'views', 'wildlife']","['backpacking', 'camping', 'hiking']",m,NaN
3310,10258707,Red Hill Overlook Summit Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.71007, 'lng': -156.25357}",8.5066,321.868,3.9624,1,out and back,NaN,4.5,31,"['dogs-no', 'kids', 'views']","['hiking', 'walking']",m,NaN
3311,10014989,Kaupo Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.64981, 'lng': -156.137}",8.3240,19312.080,1670.9136,5,out and back,1.0,4.0,8,"['dogs-no', 'views', 'wildlife']",['hiking'],m,NaN
3312,10259465,Ka Lu'u o ka O'o Cinder Cone via Crater and Sl...,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.71449, 'lng': -156.25085}",2.4176,8368.568,510.8448,3,loop,2.0,4.5,45,['views'],['hiking'],m,NaN

In [8]:
# Save all trail dataframe to a csv file in the Resources folder
park_df.to_csv('Resources/trails_park_code_cleaned.csv',index=False)