In [1]:
import pandas as pd
import requests
from config import weather_key

In [2]:
park_df = pd.read_csv('../Resources/National_Parks.csv')
park_df

,parkCode,Park Name,Fee per Car,Fee per Person,Street Address,City,State,Zip Code,Phone Number,Email Address,Lat,Lng,Weather Summary
0,acad,Acadia National Park,30.0,15.0,25 Visitor Center Road,Bar Harbor,ME,04609,2072883338,acadia_information@nps.gov,44.409286,-68.247501,"Located on Mount Desert Island in Maine, Acadi..."
1,agfo,Agate Fossil Beds National Monument,0.0,0.0,301 River Road,Harrison,NE,69346,NaN,agfo_ranger_activities@nps.gov,42.421704,-103.753886,"Summers can be very warm, high 90's to 100 wit..."
2,alka,Ala Kahakai National Historic Trail,0.0,0.0,Superintendent,Kailua-Kona,HI,96740,NaN,aric_arakaki@nps.gov,19.144668,-155.890734,Hawaiʻiʻs coast is generally sunny and hot. Be...
3,alfl,Alibates Flint Quarries National Monument,0.0,0.0,37084 Alibates Rd.,Potter County,TX,79036,NaN,lamr_interpretation@nps.gov,35.581966,-101.671701,The Texas Panhandle experiences a wide variety...
4,alpo,Allegheny Portage Railroad National Historic Site,0.0,0.0,110 Federal Park Road,Gallitzin,PA,16641,NaN,alpo_interpretation@nps.gov,40.429775,-78.574316,"The park is located in Cambria County, PA, and..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,yell,Yellowstone National Park,35.0,20.0,2 Officers Row,Yellowstone National Park,WY,82190,307-344-7381,YELL_Information@nps.gov,44.598244,-110.547169,"Yellowstone's weather can vary quite a bit, ev..."
271,york,Yorktown Battlefield Part of Colonial National...,0.0,0.0,Yorktown Battlefield,Yorktown,VA,23690,NaN,colo_info@nps.gov,37.219500,-76.498300,"Yorktown, VA climate is warm during summer whe..."
272,yose,Yosemite National Park,35.0,20.0,9039 Village Drive,Yosemite,CA,95389,209/372-0200,yose_web_manager@nps.gov,37.848833,-119.557187,"Yosemite National Park covers nearly 1,200 squ..."
273,yuch,Yukon - Charley Rivers National Preserve,0.0,0.0,101 Dunkel St,Fairbanks,AK,99701,NaN,fair_information@nps.gov,65.093561,-142.796002,The area that Yukon-Charley Rivers encompasses...
274,zion,Zion National Park,35.0,20.0,Zion National Park,Springdale,UT,84767,435-772-3256,zion_park_information@nps.gov,37.298393,-113.026514,Zion is known for a wide range of weather cond...

In [3]:
weather_df = park_df[['parkCode','Park Name','City','State','Lat','Lng']]
weather_df["Min Temp"]=""
weather_df["Max Temp"]=""
weather_df["Humidity"]=""
weather_df["Cloudiness"]=""
weather_df["Wind Speed"]=""
weather_df["Date"]=""


units = 'imperial'
weather_key=weather_key
openweather =  "https://api.openweathermap.org/data/2.5/weather?"

print("Beginning Data Retrieval")
print("-----------------------------")


for index,row in weather_df.iterrows():
    park = row["Park Name"]
    lat = row['Lat']
    lng = row['Lng']
    params = {'appid':weather_key,
             'lat':lat,
             'lon':lng}
    response = requests.get(openweather,params=params).json()
    try:
        min_temp = response["main"]["temp_min"]
        max_temp = response["main"]["temp_max"]
        humidity = response["main"]["humidity"]
        wind = response["wind"]["speed"]
        country = response["sys"]["country"]
        date = response["dt"]
        clouds = response['clouds']['all']
        weather_df.loc[index,"Humidity"]=humidity
        weather_df.loc[index,"Min Temp"]=min_temp
        weather_df.loc[index,"Max Temp"]=max_temp
        weather_df.loc[index,"Humidity"]=humidity
        weather_df.loc[index,"Cloudiness"]=clouds
        weather_df.loc[index,"Wind Speed"]=wind
        weather_df.loc[index,"Country"]=country
        weather_df.loc[index,"Date"]=date
    except:
        pass

C:\Users\nigel\AppData\Local\Temp\ipykernel_31764\3831018695.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df["Min Temp"]=""
C:\Users\nigel\AppData\Local\Temp\ipykernel_31764\3831018695.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df["Max Temp"]=""
C:\Users\nigel\AppData\Local\Temp\ipykernel_31764\3831018695.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df["Humidity"]=""
C:\Users\nigel\AppData\Local\Temp\ipykernel_31764\3831018695.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df["Cloudiness"]=""
C:\Users\nigel\AppData\Local\Temp\ipykernel_31764\3831018695.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df["Wind Speed"]=""
C:\Users\nigel\AppData\Local\Temp\ipykernel_31764\3831018695.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df["Date"]=""

Beginning Data Retrieval
-----------------------------

In [5]:
weather_df.to_csv('../Resources/cleaned/weather_data.csv',index=False)

In [6]:
weather_df

,parkCode,Park Name,City,State,Lat,Lng,Min Temp,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Country
0,acad,Acadia National Park,Bar Harbor,ME,44.409286,-68.247501,289.66,292.08,97,100,2.06,1663121480,US
1,agfo,Agate Fossil Beds National Monument,Harrison,NE,42.421704,-103.753886,294.07,296.39,14,89,4.08,1663121480,US
2,alka,Ala Kahakai National Historic Trail,Kailua-Kona,HI,19.144668,-155.890734,298.06,298.06,83,83,2.45,1663121481,US
3,alfl,Alibates Flint Quarries National Monument,Potter County,TX,35.581966,-101.671701,297.48,302.08,26,100,8.17,1663121481,US
4,alpo,Allegheny Portage Railroad National Historic Site,Gallitzin,PA,40.429775,-78.574316,284.09,285.79,89,0,3.84,1663121481,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,yell,Yellowstone National Park,Yellowstone National Park,WY,44.598244,-110.547169,285.36,285.73,62,100,0,1663121558,US
271,york,Yorktown Battlefield Part of Colonial National...,Yorktown,VA,37.219500,-76.498300,289.83,298.07,66,0,2.57,1663121558,US
272,yose,Yosemite National Park,Yosemite,CA,37.848833,-119.557187,283.19,283.57,64,47,1.57,1663121558,US
273,yuch,Yukon - Charley Rivers National Preserve,Fairbanks,AK,65.093561,-142.796002,284.75,284.75,63,98,0.9,1663121559,US
274,zion,Zion National Park,Springdale,UT,37.298393,-113.026514,287.33,289.55,74,58,0.88,1663121559,US